---
repos:
  - repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - --skip=*.css,*.js,*.map,*.scss,*.svg,*.ipynb
          - --ignore-words-list=magent
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - '--per-file-ignores=*/__init__.py:F401'
          - --extend-ignore=E203,W605,F841,E731,E741,F401 # TODO: fix some of these
          - --max-complexity=205
          - --max-line-length=300
          - --show-source
          - --statistics
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          - --source
          - --explain
          - --convention=google
          - --count
          # TODO: Remove ignoring rules D101, D102, D103, D105
          - --add-ignore=D100,D107,D101,D102,D103,D105
        exclude: "__init__.py$|^metaworld.tests|^docs"
        additional_dependencies: ["tomli"]
