# A mapping from 'TaskName' to tools that are required to complete that task
TOOLSETS = {
    'Assemble': {'ScrewEye', 'ScrewEyePeg'},
    'Basketball': {'Basketball', 'BasketballHoop'},
    'BinPicking': {'BinA', 'BinB', 'Puck'},
    'BinClose': {'BinA', 'BinLid'},
    'ButtonPress': {'ButtonBox'},
    'CoffeeButton': {'CoffeeMachine'},
    'CoffeePull': {'CoffeeMachine', 'CoffeeMug'},
    'CoffeePush': {'CoffeeMachine', 'CoffeeMug'},
    'DialTurn': {'Dial'},
    'Disassemble': {'ScrewEye', 'ScrewEyePeg'},
    'DoorClose': {'Door'},
    'DoorOpen': {'Door'},
    'DrawerClose': {'Drawer'},
    'DrawerOpen': {'Drawer'},
    'FaucetClose': {'FaucetBase'},
    'FaucetOpen': {'FaucetBase'},
    'Hammer': {'HammerBody', 'NailBox'},
    'HandlePress': {'ToasterHandle'},
    'HandlePull': {'ToasterHandle'},
    'LeverPull': {'Lever'},
    'PlugIn': {'ElectricalOutlet', 'ElectricalPlug'},
    'Unplug': {'ElectricalOutlet', 'ElectricalPlug'},
    'PickPlace': {'Puck'},
    'Reach': {},
    'ShelfPlace': {'Shelf', 'Puck'},
    'Soccer': {'SoccerGoal', 'Basketball'},
    'PushThermos': {'HammerBody', 'Thermos'},
    'PullThermos': {'HammerBody', 'Thermos'},
    'WindowOpen': {'Window'},
    'WindowClose': {'Window'},
}
